# Generated by Django 5.1.5 on 2025-06-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('diagnostico', models.CharField(max_length=300, null=True)),
                ('tratamiento', models.CharField(max_length=300, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_control', models.DateTimeField(null=True)),
                ('paciente', models.ForeignKey(db_column='paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.paciente')),
                ('profesional', models.ForeignKey(db_column='profesional', null=True, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
    ]
