# Generated by Django 5.1.5 on 2025-06-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_profesional', models.CharField(max_length=10)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30, null=True)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profesion', models.ForeignKey(db_column='profesion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesion.profesion')),
            ],
            options={
                'db_table': 'profesional',
            },
        ),
    ]
