# Generated by Django 5.1.5 on 2025-06-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sabado'), ('DO', 'Domingo')], max_length=2)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('profesional', models.ForeignKey(db_column='profesional', on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
